[development]
dynaconf_merge = true

[development.db]
echo = true
uri = "postgresql://postgres:postgres@localhost:5432/luke"

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:3000", "http://localhost:4200"]

[production]
dynaconf_merge = true

[production.db]
echo = false
uri = "postgresql://postgres:postgres@db:5432/luke"

[production.server]
log_level = "error"
reload = false

[testing]
dynaconf_merge = true

[testing.db]
uri = "postgresql://postgres:postgres@localhost:5432/postgres"

[testing.server]
cors_origins = ["http://localhost:3000", "http://localhost:4200"]
